name = input("Enter a name: ")
friend_name = input("Enter a friend's name: ")
adjective = input("Enter an adjective: ")
plural_noun = input("Enter a plural noun: ")
place = input("Enter a place: ")
noun = input("Enter a noun: ")
animal = input("Enter an animal: ")
object = input("Enter an object: ")
verb = input("Enter a verb: ")
food_item = input("Enter a food item: ")

print(f"One day, {name} and {friend_name} decided to go on a {adjective} adventure.")
print(f"They packed their {plural_noun} and set off into the {place}. Suddenly, they heard a {adjective} noise coming from behind a {noun}.")
print(f"'What was that?' {name} whispered. They turned around and saw a {adjective} {animal} holding a {object}!")
print(f"'We must {verb} before it gets us!' {friend_name} shouted.")
print(f"But before they could, the {animal} started talking and offered them a {food_item}. It was the strangest adventure ever!")
